# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-13 20:54
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doubletap', '0005_auto_20210713_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
    ]
