# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-13 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubletap', '0007_auto_20210713_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
